spring.application.name: InfluxDB App

server.port: 9080

info.name: ${spring.application.name}

influxdb:
    url: http://localhost:8086
    user: root
    password: root
    database: spica

logging.level:
    com.endava: DEBUG
    org.springframework.web: INFO
